### ISSUE TITLE
Licence type?

### ISSUE THREAD

**Issue by boettr** [findulov/EntityFrameworkCore.TemporalTables#1]
Hi,

First of all thank you for the elegant solution to the frustrating lack of support from EF Core on temporal tables.

I'm keen to use this for a project at work but notice that a licence type has not been selected yet. 

Obviously if your wishes are to not have this used in a corporate environment I respect your choice but if you are happy for it to be used would you consider tagging the repo with a MIT licence?

Thanks again

**Comment by findulov** [comment]
Hi,

Sorry for the missing license, I was so keen on providing a good solution for temporal tables in EF Core that I had forgotten to add such basic information to the project. I've added the project under MIT license and you and everyone else can use this library safely. Thank you for pointing that out.

I'd like also to thank you for your interest and your appreciation of the project and I would be happy if it's used by more people.

**Comment by boettr** [comment]
Thank you for your prompt response.

Absolutely no reason to apologise as it's an easy one to miss.
