### ISSUE TITLE
Exclude owned types

### ISSUE THREAD

**Issue by sbognarcforp** [findulov/EntityFrameworkCore.TemporalTables#3]
You should change line 15 in ModelBuilderExtensions.cs to the following:

`var entityTypes = modelBuilder.Model.GetEntityTypes().Where(e => !e.IsOwned()).ToList();`

Otherwise, using owned types and UseTemporalTables() gives you the following exception:

`System.Data.SqlClient.SqlException: 'Cannot find the object "dbo.EntityType._OwnedType" because it does not exist or you do not have permissions.'`

**Comment by findulov** [comment]
Point taken, thanks for the suggestion!
