### ISSUE TITLE
Unable to create migrations after upgrading to .NET Core 3.0

### ISSUE THREAD

**Issue by ury** [findulov/EntityFrameworkCore.TemporalTables#5]
After upgrading my solution to .NET Core 3.0, I'm unable to create migrations when using the package.
When Add-Migration is executed, it results with the following error:

Method not found: 'Void Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator..ctor(Microsoft.EntityFrameworkCore.Migrations.IMigrationsAssembly, Microsoft.EntityFrameworkCore.Migrations.IHistoryRepository, Microsoft.EntityFrameworkCore.Storage.IDatabaseCreator, Microsoft.EntityFrameworkCore.Migrations.IMigrationsSqlGenerator, Microsoft.EntityFrameworkCore.Storage.IRawSqlCommandBuilder, Microsoft.EntityFrameworkCore.Migrations.IMigrationCommandExecutor, Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, Microsoft.EntityFrameworkCore.Storage.ISqlGenerationHelper, Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<Migrations>, Microsoft.EntityFrameworkCore.Storage.IDatabaseProvider)'.

I've verified that this is related to the package:  When I remove it (together with all its references) from my project, Add-Migration is completed successfully.

**Comment by jmarbutt** [comment]
I am also having this issue.

**Comment by findulov** [comment]
I haven't played with .NET Core 3.0 yet and will "get my hands dirty" with it these days and will find out what's causing the problem and fix it.

**Comment by M2xAy** [comment]
Hi George
Firstly Thank you very much for your Project

I Updated my project to 3.0 but i receive the following exception
`System.TypeLoadException: "Could not load type 'Microsoft.EntityFrameworkCore.RelationalMetadataExtensions' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'."
`
on 
`        temporalTableSqlBuilder.BuildTemporalTablesSql();`

Metdadata API has changed 
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#metadata-api-changes

Have you any Idea ? 


Best regards

**Comment by findulov** [comment]
Hi all,

A new version of the library is released which supports .NET Core 3.0.

Thank you for being patient enough and appreciate the project.

**Comment by M2xAy** [comment]
Hi George

Thank you very much ! I will test it today

Best regards from Zurich

**Comment by ury** [comment]
Sorry for the late response, and thanks for the update - seems to be working well.
